name: ztdlbook
channels:
- defaults
dependencies:
- python=3.6
- bz2file==0.98
- cython==0.28.*
- flask==1.0.*
- gensim==3.4.*
- h5py==2.8.*
- jupyter==1.0.*
- matplotlib==2.2.*
- numpy==1.14.*
- pandas==0.23.*
- pillow==5.2.*
- pip==10.0.*
- pytest==3.7.*
- scikit-learn==0.19.*
- scipy==1.1.*
- seaborn==0.9.*
- twisted==18.7.*
- pip:
  - PyHamcrest==1.9.0
  - tensorflow==1.10.1
  - keras==2.2.2
  - jupyter_contrib_nbextensions==0.5.0
  - tensorflow-serving-api==1.10.1
  - wandb==0.6.*
